# Generated by Django 5.0.4 on 2024-04-15 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('organizer', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=255)),
                ('venue', models.CharField(choices=[('audi', 'Auditorium'), ('seminar', 'Seminar Hall'), ('conference', 'Conference Hall'), ('lab', 'Computer Labs'), ('classroom', 'Class Rooms')], max_length=50)),
                ('subvenue', models.CharField(blank=True, max_length=100, null=True)),
                ('refreshments', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], max_length=3)),
                ('chiller', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Subvenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subvenues', to='home.book')),
            ],
        ),
    ]
